apiVersion: apps/v1
kind: Deployment
metadata:
  name:  test-gin
  namespace: default
  labels:
    app:  test-gin
spec:
  selector:
    matchLabels:
      app: test-gin
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  test-gin
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  test-gin
        image:  "tae2089/gindoc:latest"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  3000
          name:  test-gin
      restartPolicy: Always