apiVersion: v1
kind: Pod
metadata:
  name: "test-gin"
  namespace: default
  labels:
    app: "test-gin"
spec:
  containers:
  - name:  test-gin
    image:  tae2089/gindoc
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
    ports:
    - containerPort:  3000