web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
        GITLAB_OMNIBUS_CONFIG: |
            external_url 'http://gitlab.example.com:8929'
            gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
        - '8929:8929'
        - '2224:22'
        - '443:443'
    volumes:
        - '/Users/imtaebin/srv/gitlab/config:/etc/gitlab'
        - '/Users/imtaebin/srv/gitlab/logs:/var/log/gitlab'
        - '/Users/imtaebin/srv/gitlab/data:/var/opt/gitlab'
        - '/Users/imtaebin/srv/gitlab/backups:/var/opt/gitlab/backups' # 백업 폴더 추가
