version: "3.7"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    tty: true
    ports:
      - "27016:27017"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    tty: true
    ports:
      - "8081:8081"
networks:
  bridge:
